post http://localhost:3002/register/
Content-Type: application/json
{
  "username":"adam_richard",
  "password":"richard_567",
  "name":"Adam Richard",
  "gender":"male"
}
###
post http://localhost:3002/login/
###
get http://localhost:3002/user/tweets/feed/
###

get http://localhost:3002/user/following/

###
DELETE  http://localhost:3002/tweets/:tweetId/